#cloud-config
autoinstall:
  version: 1
  locale: en_US
  storage:
    layout:
      name: lvm
  identity:
    hostname: burger
  ssh:
    install-server: yes
    allow-pw: no
  user-data:
    disable_root: true
    users:
      - name: rasmus
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCa0SH4aSfch9JB/Wx98JjQyBYYhJ/s3kaLkvUG8d8DIvjoZXI7+AhBRwTW/+gAZmqUOniiqPzwFfA4bAcZg3x5aK7tjk4FuKMU/Yzl8w2+Zh7TQ2oCpGS9fYURXFwJJfAGX5TEVYTN8iodaB5yxTaIxXUJXLGa8TomkYzO0D/0ETqqLPDoH84ySWEIYrs1DP3j0q5qQ3zRlJaONuPc0z4XdhKBHGetxFSx8o8+nHnL9yjKTQ/Mg9wJh8eR3R/VSMPvOBxoem1e17hAfnC509/VOEWrOvx7efhI1W0eB6P+JqX7RAXAsZR2XQTrWQHOEnyXcr6R7i0QIYBu626s3OG+bEFFdcsJ6rvsnjCtr6G02oJShwXuEBO6Gx6QMKMmoA/o4+T+WsV0NJ3CQuKvlvHRH7++3jsNvSk5nPz/VfUPBp0/9UbHllgAFnsSPYmMFjh5urBfEi5/7QZoXY3ElwR30SwMITOSj/kSzdkWSfIH177kzeEvzU4GTarDIX5Wlx2N5kwJUuosEIZHhGF67cz3YVgWSZt0ylrMDqP08SBbKw+aC9CS/4SSGx59Qla3fMX62EtwM/GHFWWgBEuJcLYSIXOiwYlO/nkZFzSraUAvub0XX+bKNUg7LnKjI1mXkOfP0YwG2xdSol+9V38BMQhMH7DzUAGL4DWwgF7rPYsJxw== rancher
        groups:
          - sudo
        sudo:
          - ALL=(ALL:ALL) ALL