#!/usr/bin/env bash
# gh-json-fields.sh — the replay fake `gh`'s `--json` field allowlist, generated from the PINNED gh.
#
#   bash agents/replay/gh-json-fields.sh            # --check (default): red when the committed list
#                                                   #   differs from what the devbox-pinned gh reports
#   bash agents/replay/gh-json-fields.sh --write    # regenerate agents/replay/stubs/gh-json-fields.tsv
#   devbox run gh-json-fields [-- --write]          # the same, through the pinned toolchain
#
# WHY (2026-10-06 23:22–23:41Z, #2333 → quickfix 914b2b3c): a clause asked `gh pr list --json
# …,lastEditedAt`. gh has no such field, so the real call died `Unknown JSON field: "lastEditedAt"`
# and every stack's review tick aborted — while the replay fixtures stayed green, because the fake
# `gh` (stubs/gh) served the recorded world for ANY field list. The fake now rejects an unknown
# field with gh's own error text, and this file is where it learns which fields exist.
#
# SOURCE OF TRUTH = the pinned gh itself, never a hand list: `gh <cmd> --json` with no fields prints
# "Specify one or more comma-separated fields for `--json`:" followed by the field list, offline
# (it fails before auth). The committed file carries the gh version line, so a gh BUMP reds the
# --check (registered as the `gh-json-fields` suite fixture, run by the full replay) until someone
# regenerates — a field gh drops in a bump then surfaces as a fixture red, not a production abort.
#
# The command list is every `gh` subcommand that takes `--json` in this gh — the fake refuses a
# `--json` call on a command NOT in the file (loud, so a new subcommand is added here, not guessed).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/stubs/gh-json-fields.tsv"
MODE="${1:---check}"

CMDS=(
  "pr list" "pr view" "pr checks" "pr status"
  "issue list" "issue view" "issue status"
  "run list" "run view"
  "repo view" "repo list"
  "search issues" "search prs" "search repos" "search commits"
  "release list" "release view"
  "workflow list" "label list" "cache list" "secret list" "variable list"
)

command -v gh >/dev/null 2>&1 || { echo "gh-json-fields: no gh on PATH — run via devbox (the pinned gh is the source of truth)" >&2; exit 2; }

render() {
  local ver c out fields
  ver="$(gh --version | sed -n '1p')"
  printf '# GENERATED by agents/replay/gh-json-fields.sh --write from the devbox-pinned gh — never hand-edit.\n'
  printf '# %s\n' "$ver"
  printf '# <gh subcommand>\\t<comma-separated --json fields>\n'
  for c in "${CMDS[@]}"; do
    # word-split on purpose: "pr list" → gh pr list --json
    # shellcheck disable=SC2086
    out="$(gh $c --json 2>&1 </dev/null || true)"
    case "$out" in
      "Specify one or more comma-separated fields for \`--json\`:"*) ;;
      *) echo "gh-json-fields: \`gh $c --json\` did not print a field list (gh changed shape?):" >&2
         printf '%s\n' "$out" >&2; return 1 ;;
    esac
    fields="$(printf '%s\n' "$out" | sed -n 's/^  \([A-Za-z][A-Za-z0-9]*\)$/\1/p' | paste -sd, -)"
    [ -n "$fields" ] || { echo "gh-json-fields: \`gh $c --json\` listed no fields" >&2; return 1; }
    printf '%s\t%s\n' "$c" "$fields"
  done
}

tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
render > "$tmp"
case "$MODE" in
  --write)
    mv "$tmp" "$OUT"; trap - EXIT
    echo "gh-json-fields: wrote $OUT ($(grep -vc '^#' "$OUT") commands)"
    ;;
  --check)
    if diff -u "$OUT" "$tmp"; then
      echo "✓ gh-json-fields: committed allowlist matches the pinned gh ($(sed -n '2p' "$OUT" | sed 's/^# //'))"
    else
      echo "✗ gh-json-fields: the committed allowlist differs from the pinned gh (above) — a gh bump? regenerate: devbox run gh-json-fields -- --write" >&2
      exit 1
    fi
    ;;
  *) echo "usage: $0 [--check|--write]" >&2; exit 2 ;;
esac
