# Remote state — homelab Garage S3 (FU-012, docs/tofu-state.md). GENERATED by
# scripts/tofu-state-migrate.sh; commit it, it is part of the root's definition.
#
# There is deliberately NO credential here: the access key, the endpoint and the state-encryption
# passphrase all come from the environment via scripts/tofu-state-env.sh, which is what makes this
# block safe to commit to a public repo. `tofu init` in this root will fail without it — that is
# the intended failure, not a bug.
terraform {
  backend "s3" {
    bucket = "homelab-tofu-state"
    key    = "cloudflare/terraform.tfstate"
    region = "garage"

    # Garage speaks S3 and nothing else AWS: no STS, no IMDS, no account id, path-style only.
    endpoints                   = { s3 = "https://s3.teststuff.net" }
    use_path_style              = true
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true

    # S3-native locking via conditional writes. scripts/tofu-state-migrate.sh probes whether Garage
    # actually enforces them and writes the ANSWER here — it never writes true on faith.
    # false, DELIBERATELY: this Garage does not enforce conditional writes (measured
    # 20/20). Safe only while this root has ONE writer — the operator. An automated APPLIER against
    # this root is blocked on real locking; docs/tofu-state.md carries the ruling.
    use_lockfile = false
  }
}
