apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-exporter-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cloudflare-exporter-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_OBSERVABILITY_READ
