apiVersion: v1
kind: Service
metadata:
  name: cloudflare-exporter
  labels: { app: cloudflare-exporter }
spec:
  selector: { app: cloudflare-exporter }
  ports:
    - { name: http, port: 8080, targetPort: http }
