#!/usr/bin/env bash
# github-apps.sh — generate docs/github-apps.md: which GitHub Apps are installed on which org repos.
#
# GitHub App installs are CLICK-ONLY (not managed by tofu/github — see new-agent-repo.sh), so there's no
# git source of truth for "which app is on which repo". This DISCOVERS the live state from the GitHub API
# and writes a markdown matrix, so the click-only state is at least documented + diffable.
#
# Run OUTSIDE the jail with an ADMIN PAT (needs `admin:org` read — the jail token 403s on
# /orgs/*/installations). The per-repo enumeration for `selected` installs uses
# /user/installations/{id}/repositories, which works when the caller is the org owner who installed them.
#
#   GH_TOKEN=<admin-pat> ORG=teststuffstash bash scripts/github-apps.sh   # or: devbox run github-apps
set -euo pipefail
ORG="${ORG:-teststuffstash}"
OUT="${OUT:-docs/github-apps.md}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"; OUT="${HERE}/${OUT}"

command -v gh >/dev/null || { echo "need gh on PATH (devbox run github-apps, or a shell with gh)"; exit 1; }
gh api "/orgs/${ORG}/installations" >/dev/null 2>&1 || {
  echo "ERROR: can't read /orgs/${ORG}/installations — this needs an ADMIN PAT (admin:org), run OUTSIDE the jail." >&2; exit 1; }

# all org repos = the columns (sorted)
mapfile -t REPOS < <(gh api "/orgs/${ORG}/repos" --paginate --jq '.[].name' | sort)

# installations = the rows:  id \t app_slug \t repository_selection
INSTALLS="$(gh api "/orgs/${ORG}/installations" --paginate --jq '.installations[] | [.id, .app_slug, .repository_selection] | @tsv')"

declare -A CELL SEL
APPS=()
while IFS=$'\t' read -r id slug selection; do
  [ -n "${slug:-}" ] || continue
  APPS+=("$slug"); SEL["$slug"]="$selection"
  if [ "$selection" = "all" ]; then
    for r in "${REPOS[@]}"; do CELL["$slug|$r"]=1; done
  else
    # best-effort: the org owner running this can usually list a selected install's repos
    while read -r r; do [ -n "$r" ] && CELL["$slug|$r"]=1; done \
      < <(gh api "/user/installations/${id}/repositories" --paginate --jq '.repositories[].name' 2>/dev/null || true)
  fi
done <<< "$INSTALLS"

{
  echo "# GitHub App installations"
  echo
  echo "_Generated by \`scripts/github-apps.sh\` on $(date -u +%Y-%m-%d). App installs are click-only (NOT tofu), so this is discovered live — regenerate after installing/removing an App. ✓ = installed; a \`selected\` row with no ✓ means the admin PAT couldn't enumerate its repos (run as the org owner)._"
  echo
  printf '| App (scope) |'; for r in "${REPOS[@]}"; do printf ' %s |' "$r"; done; printf '\n'
  printf '|---|'; for _ in "${REPOS[@]}"; do printf '---|'; done; printf '\n'
  # sort app rows for a stable diff
  while read -r a; do
    printf '| `%s` (%s) |' "$a" "${SEL[$a]}"
    for r in "${REPOS[@]}"; do [ -n "${CELL[$a|$r]:-}" ] && printf ' ✓ |' || printf '  |'; done
    printf '\n'
  done < <(printf '%s\n' "${APPS[@]}" | sort -u)
} > "$OUT"
echo "→ wrote ${OUT} (${#APPS[@]} apps × ${#REPOS[@]} repos)"
