#!/usr/bin/env python3
"""github-apps-md — generate docs/github-apps-declared.md from docs/github-apps.yaml (FU-098).

Pure derivation, no network, no credentials — CI-safe. github-apps-lint fails when the output
is stale (regenerate with `devbox run github-apps-md`), the same author-runs-generator pattern
as machines/ and merge-path-lint. The LIVE overlay (install matrix + drift verdicts) stays in
docs/github-apps.md, generated by scripts/github-apps.sh where the credentials live.
"""
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "docs", "github-apps.yaml")
OUT = os.path.join(ROOT, "docs", "github-apps-declared.md")


def main():
    apps = json.loads(subprocess.run(["yq", "-o=json", SRC], check=True,
                                     stdout=subprocess.PIPE, text=True).stdout)["apps"]
    lines = [
        "# GitHub Apps — declared state",
        "",
        "_GENERATED from [`github-apps.yaml`](github-apps.yaml) by `devbox run github-apps-md` — edit the yaml, never this file (the lint enforces sync). Change flow: PR the yaml → the `GithubAppPermissionDrift` alert rings → the operator clicks the grant → the alert clears. Live install matrix + drift verdicts: [`github-apps.md`](github-apps.md)._",
        "",
    ]
    for a in apps:
        lines.append(f"## `{a['slug']}`")
        lines.append("")
        lines.append(str(a.get("purpose", "")).strip())
        ids = f"app_id `{a.get('app_id')}`" if a.get("app_id") else "app_id _unfilled_"
        inst = f"install_id `{a.get('install_id')}`" if a.get("install_id") else ""
        lines.append("")
        lines.append(f"_{ids}{' · ' + inst if inst else ''} · installs: **{a.get('installs', '?')}** · keys: {', '.join(str(k) for k in a.get('key_locations', []))}_")
        lines.append("")
        lines.append("| Permission | Level | Why |")
        lines.append("|---|---|---|")
        for perm, spec in (a.get("permissions") or {}).items():
            lines.append(f"| `{perm}` | {spec['level']} | {spec['why']} |")
        for perm, why in (a.get("absent") or {}).items():
            lines.append(f"| `{perm}` | **absent (decided)** | {why} |")
        if a.get("note"):
            lines.append("")
            lines.append(f"> {a['note']}")
        lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(apps)} apps)")


if __name__ == "__main__":
    main()
