#!/usr/bin/env python3
"""merge-path-lint — the living-documentation gate for the merge-path FSMs (2026-07-21, after the
nine-review loop: the fourth unmodeled-transition incident).

Reads the FSM models (docs/agents/merge-path-fsm.yaml = the APP-REPO machine;
docs/agents/iac-lane-fsm.yaml = the -IAC machine, FU-106) and for each:
  1. LINTS it against the code: every guard/belt anchor (file + regex) must still grep — a fix
     that moves or a guard that gets deleted fails CI instead of silently un-guarding a
     transition (the registration-lint pattern applied to the state machine).
  2. Checks every gap carries an fu:/accepted: disposition — known-missing guards are first-class
     records, never prose folklore.
  2b. THE ORPHAN GATE (ADR-103, landed 2026-08-10): every `guarded` transition must declare
     either `replay:` (fixture dirs / replay scripts that EXIST — the executed-replay coupling)
     or `unreplayed: "<reason>"` (an explicit, rendered admission — the oracle evidence-lint's
     "covered or explicitly unverified" rule, checks C/D, transposed). Coverage becomes a
     rendered fact instead of an audit; fixtures no transition references are listed for
     visibility (helper-level pins are legitimate).
  3. GENERATES the sibling .md (--write): the mermaid diagram + the transition/guard/incident
     table + the gap register. The .md is generated output; hand-edits die on the next run by
     design. The diagram + title + narrative link live IN the model YAML.

Usage: merge-path-lint.py [--write]     (devbox run merge-path-lint [-- --write])
Anchors with repo: other than homelab are checked only if that repo is checked out as a sibling
(/workspace/<repo> or ../<repo>); absent siblings are reported as SKIPPED, never failed — CI has
only the homelab checkout.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # noqa: F401 — preferred when present
    def load_model(path):
        return yaml.safe_load(path.read_text())
except ModuleNotFoundError:  # devbox python is stdlib-only — yq (in the toolchain) converts
    def load_model(path):
        out = subprocess.run(["yq", "-o=json", str(path)], capture_output=True, text=True, check=True)
        return json.loads(out.stdout)

ROOT = Path(__file__).resolve().parent.parent
MODELS = [
    (ROOT / "docs/agents/merge-path-fsm.yaml", ROOT / "docs/agents/merge-path-fsm.md"),
    (ROOT / "docs/agents/iac-lane-fsm.yaml", ROOT / "docs/agents/iac-lane-fsm.md"),
    # The ISSUE machine (goal lane included) — merge-path models the PR, this models the issue
    # whose close the PR's merge is (FU-143 arc, 2026-08-06).
    (ROOT / "docs/agents/issue-lifecycle-fsm.yaml", ROOT / "docs/agents/issue-lifecycle-fsm.md"),
]


def resolve_repo(repo: str | None) -> Path | None:
    if not repo or repo == "homelab":
        return ROOT
    for base in (ROOT.parent, Path("/workspace")):
        p = base / repo
        if p.is_dir():
            return p
    return None


def check_anchor(anchor: dict) -> str:
    base = resolve_repo(anchor.get("repo"))
    if base is None:
        return "SKIPPED (repo not checked out)"
    path = base / anchor["file"]
    if not path.is_file():
        return f"MISSING FILE {path}"
    try:
        text = path.read_text(errors="replace")
    except Exception as e:  # noqa: BLE001
        return f"UNREADABLE ({e})"
    if re.search(anchor["pattern"], text):
        return "ok"
    return f"ANCHOR NOT FOUND: /{anchor['pattern']}/ in {anchor['file']}"


REFERENCED_FIXTURES: set[str] = set()


def render(model: dict, model_path: Path, failures: list[str]) -> list[str]:
    narrative = model["narrative"]
    lines = [
        f"# {model['title']} — transitions, guards, gaps (GENERATED)",
        "",
        "> **GENERATED by `devbox run merge-path-lint -- --write` from "
        f"[`{model_path.name}`]({model_path.name}) — edit the YAML, never this file.**",
        "> The lint greps every guard's code anchor on each run: a moved/deleted guard fails CI",
        "> instead of silently un-guarding a transition. Design narrative: "
        f"[`{narrative}`]({narrative}).",
        "",
        "## The machine",
        "",
        "```mermaid",
    ]
    lines += model["diagram"].rstrip("\n").split("\n")
    lines += [
        "```",
        "",
        "## Transitions",
        "",
        "| id | transition | owner | status | guards (anchored) | belts | incidents |",
        "|---|---|---|---|---|---|---|",
    ]

    for t in model["transitions"]:
        guard_bits, belt_bits = [], []
        for kind, target in (("guards", guard_bits), ("belts", belt_bits)):
            for g in t.get(kind, []) or []:
                verdict = check_anchor(g["anchor"])
                foreign = g["anchor"].get("repo") not in (None, "homelab")
                if foreign:
                    # Sibling checkouts drift (branches, staleness) and their guards are their
                    # own CI's job — advisory only. The MARK must be constant: the live verdict
                    # depends on which siblings are checked out (CI has none, the jail has some),
                    # and an environment-dependent mark makes the generated doc perpetually
                    # "stale" in whichever environment didn't --write it. Verdict → console.
                    mark = "🔗"
                    if verdict != "ok":
                        print(f"  ⚠ {t['id']}: {g['desc']} — {verdict} (foreign repo, advisory)")
                else:
                    mark = "✅" if verdict == "ok" else "❌"
                    if mark == "❌":
                        failures.append(f"{t['id']}: {g['desc']} — {verdict}")
                loc = f"{g['anchor'].get('repo', 'homelab')}:{g['anchor']['file']}"
                target.append(f"{mark} {g['desc']} (`{loc}`)")
        status = t.get("status", "?")
        if status == "gap":
            failures.append(f"{t['id']} carries status: gap — gaps belong in the gaps: register")
        # The ADR-103 orphan gate (2b in the docstring): guarded ⇒ replay: or unreplayed:.
        replay_paths = t.get("replay") or []
        unreplayed = t.get("unreplayed")
        replay_note = ""
        if replay_paths:
            for rp in replay_paths:
                if not (ROOT / rp).exists():
                    failures.append(f"{t['id']}: replay path does not exist: {rp}")
                if rp.startswith("agents/replay/fixtures/"):
                    REFERENCED_FIXTURES.add(Path(rp).name)
            replay_note = f" · replay: {', '.join(Path(rp).name for rp in replay_paths)}"
        elif unreplayed:
            replay_note = f" · ⚠ unreplayed: {unreplayed}"
        elif status == "guarded":
            failures.append(
                f"{t['id']}: guarded transition with neither replay: nor unreplayed: — "
                "declare the fixture or admit the absence (the ADR-103 orphan gate)")
        acc = f" · accepted: {t['accepted']}" if t.get("accepted") else ""
        lines.append(
            f"| **{t['id']}** | {t['name']} | {t['owner']} | {status}{acc}{replay_note} | "
            f"{'<br>'.join(guard_bits) or '—'} | {'<br>'.join(belt_bits) or '—'} | "
            f"{'; '.join(t.get('incidents', [])) or '—'} |"
        )

    lines += ["", "## Gap register — known-missing guards", "",
              "| id | gap | detail | disposition |", "|---|---|---|---|"]
    for g in model["gaps"]:
        disp = f"FU: {g['fu']}" if g.get("fu") else (f"accepted: {g['accepted']}" if g.get("accepted") else None)
        if disp is None:
            failures.append(f"{g['id']}: gap without fu:/accepted: disposition")
            disp = "❌ UNDISPOSITIONED"
        lines.append(f"| **{g['id']}** | {g['name']} | {g['detail']} | {disp} |")

    lines += ["", f"_States/axes: {', '.join(model['axes'].keys())} · events: {len(model['events'])} · "
              f"transitions: {len(model['transitions'])} · open gaps: "
              f"{sum(1 for g in model['gaps'] if g.get('fu'))} (+{sum(1 for g in model['gaps'] if g.get('accepted'))} accepted)_", ""]
    return lines


def main() -> int:
    failures: list[str] = []
    totals = {"transitions": 0, "gaps": 0}
    for model_path, out_path in MODELS:
        model = load_model(model_path)
        lines = render(model, model_path, failures)
        totals["transitions"] += len(model["transitions"])
        totals["gaps"] += len(model["gaps"])
        if "--write" in sys.argv:
            out_path.write_text("\n".join(lines))
            print(f"wrote {out_path.relative_to(ROOT)}")
        elif out_path.exists() and out_path.read_text() != "\n".join(lines):
            failures.append(f"{out_path.name} is stale — run: devbox run merge-path-lint -- --write")

    fixtures_dir = ROOT / "agents/replay/fixtures"
    if fixtures_dir.is_dir():
        unref = [p.name for p in sorted(fixtures_dir.iterdir())
                 if p.is_dir() and not p.name.startswith("_selftest")
                 and p.name not in REFERENCED_FIXTURES]
        if unref:
            print(f"  ℹ fixtures no FSM transition references (helper-level pins — visibility, "
                  f"not failure): {', '.join(unref)}")

    if failures:
        print("merge-path-lint FAILURES:")
        for f in failures:
            print(f"  ✗ {f}")
        return 1
    print(f"merge-path-lint: {totals['transitions']} transitions anchored across {len(MODELS)} machines, "
          f"{totals['gaps']} gaps dispositioned — models match code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
