#!/usr/bin/env python3
"""merge-path-lint — the living-documentation gate for the merge-path FSMs (2026-07-21, after the
nine-review loop: the fourth unmodeled-transition incident).

Reads the FSM models (docs/agents/merge-path-fsm.yaml = the APP-REPO machine;
docs/agents/iac-lane-fsm.yaml = the -IAC machine, FU-106) and for each:
  1. LINTS it against the code: every guard/belt anchor (file + regex) must still grep — a fix
     that moves or a guard that gets deleted fails CI instead of silently un-guarding a
     transition (the registration-lint pattern applied to the state machine).
  2. Checks every gap carries an fu:/accepted: disposition — known-missing guards are first-class
     records, never prose folklore.
  2b. THE ORPHAN GATE (ADR-103, landed 2026-08-10): every `guarded` transition must declare
     either `replay:` (fixture dirs / replay scripts that EXIST — the executed-replay coupling)
     or `unreplayed: "<reason>"` (an explicit, rendered admission — the oracle evidence-lint's
     "covered or explicitly unverified" rule, checks C/D, transposed). Coverage becomes a
     rendered fact instead of an audit; fixtures no transition references are listed for
     visibility (helper-level pins are legitimate).
  3. GENERATES the sibling .md (--write): the mermaid diagram + the transition/guard/incident
     table + the gap register. The .md is generated output; hand-edits die on the next run by
     design. The diagram + title + narrative link live IN the model YAML.

Usage: merge-path-lint.py [--write]     (devbox run merge-path-lint [-- --write])
Anchors with repo: other than homelab are checked only if that repo is checked out as a sibling
(/workspace/<repo> or ../<repo>); absent siblings are reported as SKIPPED, never failed — CI has
only the homelab checkout.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # noqa: F401 — preferred when present
    def load_model(path):
        return yaml.safe_load(path.read_text())
except ModuleNotFoundError:  # devbox python is stdlib-only — yq (in the toolchain) converts
    def load_model(path):
        out = subprocess.run(["yq", "-o=json", str(path)], capture_output=True, text=True, check=True)
        return json.loads(out.stdout)

ROOT = Path(__file__).resolve().parent.parent
MODELS = [
    (ROOT / "docs/agents/merge-path-fsm.yaml", ROOT / "docs/agents/merge-path-fsm.md"),
    (ROOT / "docs/agents/iac-lane-fsm.yaml", ROOT / "docs/agents/iac-lane-fsm.md"),
    # The ISSUE machine (goal lane included) — merge-path models the PR, this models the issue
    # whose close the PR's merge is (FU-143 arc, 2026-08-06).
    (ROOT / "docs/agents/issue-lifecycle-fsm.yaml", ROOT / "docs/agents/issue-lifecycle-fsm.md"),
]


def resolve_repo(repo: str | None) -> Path | None:
    if not repo or repo == "homelab":
        return ROOT
    for base in (ROOT.parent, Path("/workspace")):
        p = base / repo
        if p.is_dir():
            return p
    return None


def check_anchor(anchor: dict) -> str:
    base = resolve_repo(anchor.get("repo"))
    if base is None:
        return "SKIPPED (repo not checked out)"
    path = base / anchor["file"]
    if not path.is_file():
        return f"MISSING FILE {path}"
    try:
        text = path.read_text(errors="replace")
    except Exception as e:  # noqa: BLE001
        return f"UNREADABLE ({e})"
    if re.search(anchor["pattern"], text):
        return "ok"
    return f"ANCHOR NOT FOUND: /{anchor['pattern']}/ in {anchor['file']}"


REFERENCED_FIXTURES: set[str] = set()


def render(model: dict, model_path: Path, failures: list[str]) -> list[str]:
    narrative = model["narrative"]
    lines = [
        f"# {model['title']} — transitions, guards, gaps (GENERATED)",
        "",
        "> **GENERATED by `devbox run merge-path-lint -- --write` from "
        f"[`{model_path.name}`]({model_path.name}) — edit the YAML, never this file.**",
        "> The lint greps every guard's code anchor on each run: a moved/deleted guard fails CI",
        "> instead of silently un-guarding a transition. Design narrative: "
        f"[`{narrative}`]({narrative}).",
        "",
        "## The machine",
        "",
        "```mermaid",
    ]
    lines += model["diagram"].rstrip("\n").split("\n")
    lines += [
        "```",
        "",
        "## Transitions",
        "",
        "| id | transition | owner | status | guards (anchored) | belts | incidents |",
        "|---|---|---|---|---|---|---|",
    ]

    for t in model["transitions"]:
        guard_bits, belt_bits = [], []
        for kind, target in (("guards", guard_bits), ("belts", belt_bits)):
            for g in t.get(kind, []) or []:
                verdict = check_anchor(g["anchor"])
                foreign = g["anchor"].get("repo") not in (None, "homelab")
                if foreign:
                    # Sibling checkouts drift (branches, staleness) and their guards are their
                    # own CI's job — advisory only. The MARK must be constant: the live verdict
                    # depends on which siblings are checked out (CI has none, the jail has some),
                    # and an environment-dependent mark makes the generated doc perpetually
                    # "stale" in whichever environment didn't --write it. Verdict → console.
                    mark = "🔗"
                    if verdict != "ok":
                        print(f"  ⚠ {t['id']}: {g['desc']} — {verdict} (foreign repo, advisory)")
                else:
                    mark = "✅" if verdict == "ok" else "❌"
                    if mark == "❌":
                        failures.append(f"{t['id']}: {g['desc']} — {verdict}")
                loc = f"{g['anchor'].get('repo', 'homelab')}:{g['anchor']['file']}"
                target.append(f"{mark} {g['desc']} (`{loc}`)")
        status = t.get("status", "?")
        if status == "gap":
            failures.append(f"{t['id']} carries status: gap — gaps belong in the gaps: register")
        # The ADR-103 orphan gate (2b in the docstring): guarded ⇒ replay: or unreplayed:.
        replay_paths = t.get("replay") or []
        unreplayed = t.get("unreplayed")
        replay_note = ""
        if replay_paths:
            for rp in replay_paths:
                if not (ROOT / rp).exists():
                    failures.append(f"{t['id']}: replay path does not exist: {rp}")
                if rp.startswith("agents/replay/fixtures/"):
                    # keyed by RELPATH (fixtures/<family>/<fixture>) so two families sharing a
                    # leaf name (probe-fail, both, clear…) never cross-wire in the register
                    REFERENCED_FIXTURES.add(rp[len("agents/replay/fixtures/"):].rstrip("/"))
            replay_note = f" · replay: {', '.join(Path(rp).name for rp in replay_paths)}"
        elif unreplayed:
            replay_note = f" · ⚠ unreplayed: {unreplayed}"
        elif status == "guarded":
            failures.append(
                f"{t['id']}: guarded transition with neither replay: nor unreplayed: — "
                "declare the fixture or admit the absence (the ADR-103 orphan gate)")
        acc = f" · accepted: {t['accepted']}" if t.get("accepted") else ""
        lines.append(
            f"| **{t['id']}** | {t['name']} | {t['owner']} | {status}{acc}{replay_note} | "
            f"{'<br>'.join(guard_bits) or '—'} | {'<br>'.join(belt_bits) or '—'} | "
            f"{'; '.join(t.get('incidents', [])) or '—'} |"
        )

    lines += ["", "## Gap register — known-missing guards", "",
              "| id | gap | detail | disposition |", "|---|---|---|---|"]
    for g in model["gaps"]:
        disp = f"FU: {g['fu']}" if g.get("fu") else (f"accepted: {g['accepted']}" if g.get("accepted") else None)
        if disp is None:
            failures.append(f"{g['id']}: gap without fu:/accepted: disposition")
            disp = "❌ UNDISPOSITIONED"
        lines.append(f"| **{g['id']}** | {g['name']} | {g['detail']} | {disp} |")

    lines += ["", f"_States/axes: {', '.join(model['axes'].keys())} · events: {len(model['events'])} · "
              f"transitions: {len(model['transitions'])} · open gaps: "
              f"{sum(1 for g in model['gaps'] if g.get('fu'))} (+{sum(1 for g in model['gaps'] if g.get('accepted'))} accepted)_", ""]
    return lines


def read_fixture_pins(path: Path) -> set[str]:
    """Read the `pins:` list from a fixture.yaml using the harness's OWN subset rules.

    A fixture.yaml is deliberately NOT full YAML — the harness parses only `key: value` scalars
    and `- item` lists (run.sh's parse_fixture), and the `scrub:` sed patterns contain `: ` which
    yq/pyyaml reject. So this mirrors parse_fixture's two line shapes for the ONE key the
    bidirectional lint needs: `pins:` followed by `- <id>` items (the block-list form the harness
    parser emits as `L pins <id>`), plus the inline `pins: [A, B]` scalar form. Anything else is
    ignored — this is a narrow field read, not a reimplementation of the harness.
    """
    pins: set[str] = set()
    cur: str | None = None
    with open(path) as f:
        for raw in f:
            s = raw.strip()
            if not s or s.startswith("#"):
                continue
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):(.*)$", s)
            if m:
                cur, rest = m.group(1), m.group(2).strip()
                if cur == "pins" and rest.startswith("[") and rest.endswith("]"):
                    for item in rest[1:-1].split(","):
                        item = item.strip().strip("\"'")
                        if item:
                            pins.add(item)
                continue
            m = re.match(r"^-(.*)$", s)
            if m and cur == "pins":
                v = m.group(1).strip().strip("\"'")
                if v:
                    pins.add(v)
    return pins


def check_pins_agreement(fixtures_dir: Path, failures: list[str]) -> None:
    """FU-167 move 4, direction B: the bidirectional `pins:` ↔ FSM `replay:` agreement lint.

    The FSM stays the model home — this checks agreement, it never generates either side.
    Direction A (replay: paths must exist) lives in render(); here we add direction B:
      * every fixture declaring `pins: [X]` must be named by transition X's `replay:` list;
      * every fixture named by a transition's `replay:` list must declare that transition in
        its `pins:`.
    Disagreement in either direction is a red with BOTH sides printed. A fixture with no
    `pins:` is legal (not everything pins a transition). Tables (mode: table) carry pins on
    the family fixture.yaml, so they are covered here like any other fixture.
    """
    if not fixtures_dir.is_dir():
        return
    # transition id -> sorted fixture relpaths, from the FSM replay: lists
    fsm: dict[str, set[str]] = {}
    for y in sorted((ROOT / "docs/agents").glob("*-fsm.yaml")):
        model = load_model(y)
        for t in model["transitions"]:
            for rp in t.get("replay") or []:
                if rp.startswith("agents/replay/fixtures/"):
                    fsm.setdefault(t["id"], set()).add(rp[len("agents/replay/fixtures/"):].rstrip("/"))

    # fixture relpath -> set of declared pins (from fixture.yaml)
    declared: dict[str, set[str]] = {}
    for p in sorted(fixtures_dir.iterdir()):
        if not p.is_dir():
            continue
        if (p / "fixture.yaml").is_file():
            cands = [p]
        else:
            cands = [c for c in sorted(p.iterdir()) if (c / "fixture.yaml").is_file()]
        for c in cands:
            rel = str(c.relative_to(fixtures_dir))
            pins = read_fixture_pins(c / "fixture.yaml")
            if pins:
                declared[rel] = pins

    # direction B1: fixture pins:X ⇒ X's replay: list names the fixture
    for rel, pins in sorted(declared.items()):
        for tid in sorted(pins):
            if tid not in fsm:
                failures.append(
                    f"pins agreement ({rel}): declares pins: [{tid}] but no FSM transition "
                    f"{tid} has a replay: list — the transition id is unknown or unpinned")
                continue
            if rel not in fsm[tid]:
                failures.append(
                    f"pins agreement ({rel}): declares pins: [{tid}] but {tid}'s replay: list "
                    f"does not name {rel}\n"
                    f"    fixture says: pins: [{', '.join(sorted(pins))}]\n"
                    f"    {tid} says:    replay: [fixtures/{rel}] is NOT among "
                    f"{', '.join(sorted('fixtures/' + r for r in fsm[tid]))}")

    # direction B2: FSM replay: names a fixture ⇒ that fixture declares the transition in pins:
    for tid, rels in sorted(fsm.items()):
        for rel in sorted(rels):
            fx_pins = declared.get(rel, set())
            if tid not in fx_pins:
                failures.append(
                    f"pins agreement (fsm {tid}): {tid}'s replay: list names "
                    f"fixtures/{rel}, but that fixture does not declare pins: [{tid}]\n"
                    f"    {tid} says:    replay: [fixtures/{rel}]\n"
                    f"    fixture says: pins: [{', '.join(sorted(fx_pins)) or '—'}]")


def main() -> int:
    failures: list[str] = []
    totals = {"transitions": 0, "gaps": 0}
    for model_path, out_path in MODELS:
        model = load_model(model_path)
        lines = render(model, model_path, failures)
        totals["transitions"] += len(model["transitions"])
        totals["gaps"] += len(model["gaps"])
        if "--write" in sys.argv:
            out_path.write_text("\n".join(lines))
            print(f"wrote {out_path.relative_to(ROOT)}")
        elif out_path.exists() and out_path.read_text() != "\n".join(lines):
            failures.append(f"{out_path.name} is stale — run: devbox run merge-path-lint -- --write")

    fixtures_dir = ROOT / "agents/replay/fixtures"
    if fixtures_dir.is_dir():
        # FU-167 move 5: a fixture lives at depth 1 (table) OR depth 2 (fixtures/<family>/<fixture>).
        # Unref is keyed by RELPATH so the visibility line names actual fixtures, not family dirs.
        def is_fixture(p: Path) -> bool:
            return p.is_dir() and (p / "fixture.yaml").is_file()

        def not_selftest(rel: str) -> bool:
            return not rel.split("/")[0].startswith("_selftest")

        unref = []
        for p in sorted(fixtures_dir.iterdir()):
            if p.is_dir():
                if is_fixture(p):
                    rel = p.relative_to(fixtures_dir)
                    if not_selftest(str(rel)) and str(rel) not in REFERENCED_FIXTURES:
                        unref.append(str(rel))
                else:
                    for leaf in sorted(p.iterdir()):
                        rel = str(leaf.relative_to(fixtures_dir))
                        if is_fixture(leaf) and not_selftest(rel) and rel not in REFERENCED_FIXTURES:
                            unref.append(rel)
        if unref:
            print(f"  ℹ fixtures no FSM transition references (helper-level pins — visibility, "
                  f"not failure): {', '.join(unref)}")

    # FU-167 move 4, direction B: the bidirectional pins: ↔ replay: agreement lint
    check_pins_agreement(fixtures_dir, failures)

    if failures:
        print("merge-path-lint FAILURES:")
        for f in failures:
            print(f"  ✗ {f}")
        return 1
    print(f"merge-path-lint: {totals['transitions']} transitions anchored across {len(MODELS)} machines, "
          f"{totals['gaps']} gaps dispositioned — models match code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
