#!/usr/bin/env python3
"""merge-path-lint — the living-documentation gate for the merge-path FSM (2026-07-21, after the
nine-review loop: the fourth unmodeled-transition incident).

Reads docs/agents/merge-path-fsm.yaml (THE model) and:
  1. LINTS it against the code: every guard/belt anchor (file + regex) must still grep — a fix
     that moves or a guard that gets deleted fails CI instead of silently un-guarding a
     transition (the registration-lint pattern applied to the state machine).
  2. Checks every gap carries an fu:/accepted: disposition — known-missing guards are first-class
     records, never prose folklore.
  3. GENERATES docs/agents/merge-path-fsm.md (--write): the mermaid diagram + the
     transition/guard/incident table + the gap register. The .md is generated output; hand-edits
     die on the next run by design.

Usage: merge-path-lint.py [--write]     (devbox run merge-path-lint [-- --write])
Anchors with repo: other than homelab are checked only if that repo is checked out as a sibling
(/workspace/<repo> or ../<repo>); absent siblings are reported as SKIPPED, never failed — CI has
only the homelab checkout.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # noqa: F401 — preferred when present
    def load_model(path):
        return yaml.safe_load(path.read_text())
except ModuleNotFoundError:  # devbox python is stdlib-only — yq (in the toolchain) converts
    def load_model(path):
        out = subprocess.run(["yq", "-o=json", str(path)], capture_output=True, text=True, check=True)
        return json.loads(out.stdout)

ROOT = Path(__file__).resolve().parent.parent
MODEL = ROOT / "docs/agents/merge-path-fsm.yaml"
OUT = ROOT / "docs/agents/merge-path-fsm.md"


def resolve_repo(repo: str | None) -> Path | None:
    if not repo or repo == "homelab":
        return ROOT
    for base in (ROOT.parent, Path("/workspace")):
        p = base / repo
        if p.is_dir():
            return p
    return None


def check_anchor(anchor: dict) -> str:
    base = resolve_repo(anchor.get("repo"))
    if base is None:
        return "SKIPPED (repo not checked out)"
    path = base / anchor["file"]
    if not path.is_file():
        return f"MISSING FILE {path}"
    try:
        text = path.read_text(errors="replace")
    except Exception as e:  # noqa: BLE001
        return f"UNREADABLE ({e})"
    if re.search(anchor["pattern"], text):
        return "ok"
    return f"ANCHOR NOT FOUND: /{anchor['pattern']}/ in {anchor['file']}"


def main() -> int:
    model = load_model(MODEL)
    failures: list[str] = []
    lines: list[str] = []

    lines += [
        "# Merge-path FSM — transitions, guards, gaps (GENERATED)",
        "",
        "> **GENERATED by `devbox run merge-path-lint -- --write` from "
        "[`merge-path-fsm.yaml`](merge-path-fsm.yaml) — edit the YAML, never this file.**",
        "> The lint greps every guard's code anchor on each run: a moved/deleted guard fails CI",
        "> instead of silently un-guarding a transition. Design narrative: "
        "[`merge-path.md`](merge-path.md).",
        "",
        "## The machine",
        "",
        "```mermaid",
        "stateDiagram-v2",
        "    [*] --> Open: pr_opened + arm (MP-T01)",
        "    Open --> Green: ci success",
        "    Open --> Red: ci failure",
        "    Red --> Green: fix round lands (MP-T07) — ⚠ MP-G01 no timer owner",
        "    Green --> Behind: master_moved",
        "    Behind --> Green: branch_updated (MP-T02) — NOT new content",
        "    Behind --> Conflicted: merge_conflict_422 (MP-T06)",
        "    Green --> BotApproved: review dispatch + APPROVE (MP-T03)",
        "    Green --> ChangesRequested: review dispatch + CHANGES (MP-T03)",
        "    ChangesRequested --> Green: content_pushed, re-reviewable (MP-T04/T07)",
        "    BotApproved --> CodeownerPark: spec-gated (MP-T08)",
        "    CodeownerPark --> Merged: human_approve → auto-merge (MP-T05)",
        "    BotApproved --> Merged: auto-merge (MP-T05)",
        "    Merged --> [*]: Fixes closes issue — ⚠ MP-G03 close-the-loop is manual",
        "    note right of Green",
        "        agent_error (MP-T09) freezes any state",
        "        for automation until a human clears it",
        "    end note",
        "```",
        "",
        "## Transitions",
        "",
        "| id | transition | owner | status | guards (anchored) | belts | incidents |",
        "|---|---|---|---|---|---|---|",
    ]

    for t in model["transitions"]:
        guard_bits, belt_bits = [], []
        for kind, target in (("guards", guard_bits), ("belts", belt_bits)):
            for g in t.get(kind, []) or []:
                verdict = check_anchor(g["anchor"])
                foreign = g["anchor"].get("repo") not in (None, "homelab")
                mark = "✅" if verdict == "ok" else ("⏭" if verdict.startswith("SKIPPED") else "❌")
                if mark == "❌":
                    if foreign:
                        # Sibling checkouts drift (branches, staleness) and their guards are their
                        # own CI's job — report, never fail homelab CI on them.
                        mark = "⚠"
                        print(f"  ⚠ {t['id']}: {g['desc']} — {verdict} (foreign repo, advisory)")
                    else:
                        failures.append(f"{t['id']}: {g['desc']} — {verdict}")
                loc = f"{g['anchor'].get('repo', 'homelab')}:{g['anchor']['file']}"
                target.append(f"{mark} {g['desc']} (`{loc}`)")
        status = t.get("status", "?")
        if status == "gap":
            failures.append(f"{t['id']} carries status: gap — gaps belong in the gaps: register")
        acc = f" · accepted: {t['accepted']}" if t.get("accepted") else ""
        lines.append(
            f"| **{t['id']}** | {t['name']} | {t['owner']} | {status}{acc} | "
            f"{'<br>'.join(guard_bits) or '—'} | {'<br>'.join(belt_bits) or '—'} | "
            f"{'; '.join(t.get('incidents', [])) or '—'} |"
        )

    lines += ["", "## Gap register — known-missing guards", "",
              "| id | gap | detail | disposition |", "|---|---|---|---|"]
    for g in model["gaps"]:
        disp = f"FU: {g['fu']}" if g.get("fu") else (f"accepted: {g['accepted']}" if g.get("accepted") else None)
        if disp is None:
            failures.append(f"{g['id']}: gap without fu:/accepted: disposition")
            disp = "❌ UNDISPOSITIONED"
        lines.append(f"| **{g['id']}** | {g['name']} | {g['detail']} | {disp} |")

    lines += ["", f"_States/axes: {', '.join(model['axes'].keys())} · events: {len(model['events'])} · "
              f"transitions: {len(model['transitions'])} · open gaps: "
              f"{sum(1 for g in model['gaps'] if g.get('fu'))} (+{sum(1 for g in model['gaps'] if g.get('accepted'))} accepted)_", ""]

    if "--write" in sys.argv:
        OUT.write_text("\n".join(lines))
        print(f"wrote {OUT.relative_to(ROOT)}")
    elif OUT.exists() and OUT.read_text() != "\n".join(lines):
        failures.append("merge-path-fsm.md is stale — run: devbox run merge-path-lint -- --write")

    if failures:
        print("merge-path-lint FAILURES:")
        for f in failures:
            print(f"  ✗ {f}")
        return 1
    print(f"merge-path-lint: {len(model['transitions'])} transitions anchored, "
          f"{len(model['gaps'])} gaps dispositioned — model matches code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
