#!/bin/bash
# upstream-alerts-refresh — re-render the alert names the PINNED kube-prometheus-stack chart ships
# (with our values), into argocd/platform/values/kube-prometheus-stack-upstream-alerts.txt.
# Run after a chart bump: prometheus-rules-lint reds until the list matches the pinned version, and
# then names any upstream alert that still needs a triage entry in kube-prometheus-stack-triage.yaml.
# Needs the network (helm pull) — that is why the lint itself never runs this.
#   devbox run -- bash scripts/upstream-alerts-refresh.sh
set -euo pipefail
cd "$(dirname "$0")/.."
app=argocd/platform/kube-prometheus-stack.yaml
values=argocd/platform/values/kube-prometheus-stack.yaml
out=argocd/platform/values/kube-prometheus-stack-upstream-alerts.txt
repo=$(yq -r '.spec.sources[] | select(.chart == "kube-prometheus-stack") | .repoURL' "$app")
ver=$(yq -r '.spec.sources[] | select(.chart == "kube-prometheus-stack") | .targetRevision' "$app")
[ -n "$ver" ] && [ "$ver" != "null" ] || { echo "upstream-alerts-refresh: no pinned chart version in $app" >&2; exit 2; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
helm pull kube-prometheus-stack --repo "$repo" --version "$ver" --untar --untardir "$tmp" >/dev/null
helm template kps "$tmp/kube-prometheus-stack" -f "$values" --namespace monitoring > "$tmp/rendered.yaml"
# our own groups (additionalPrometheusRulesMap) render into the same output — exclude them by name
ours=$(yq -o=json '[.additionalPrometheusRulesMap[].groups[].name]' "$values")
names=$(yq eval-all -o=json 'select(.kind == "PrometheusRule") | .spec.groups' "$tmp/rendered.yaml" \
  | jq -s -r --argjson ours "$ours" '[.[] | select(type == "array") | .[] | select(.name | IN($ours[]) | not)
                                       | .rules[] | select(.alert) | .alert] | unique[]')
[ -n "$names" ] || { echo "upstream-alerts-refresh: rendered zero upstream alerts — refusing to write an empty list" >&2; exit 2; }
{
  echo "# chart: kube-prometheus-stack $ver — every alert the PINNED chart renders with our values (the values file's own rule groups excluded)."
  echo "# Generated by scripts/upstream-alerts-refresh.sh; do not hand-edit. Each name needs one entry in kube-prometheus-stack-triage.yaml."
  echo "# defaultRules: $(yq -o=json '.defaultRules' "$values" | sha256sum | cut -c1-12)"
  printf '%s\n' "$names"
} > "$out"
echo "upstream-alerts-refresh: $(printf '%s\n' "$names" | wc -l) alert(s) for chart $ver → $out"
