#!/bin/bash
# upstream-alerts-refresh — re-render the alert names the PINNED kube-prometheus-stack chart ships
# (with our values), into argocd/platform/values/kube-prometheus-stack-upstream-alerts.txt.
# Run after a chart bump: prometheus-rules-lint reds until the list matches the pinned version, and
# then names any upstream alert that still needs a triage entry in kube-prometheus-stack-triage.yaml.
# Needs the network (helm pull) — that is why the lint itself never runs this.
#
# TWO CALLERS, one script (gap register G12, docs/dependency-upgrades.md):
#   the seat   devbox run -- bash scripts/upstream-alerts-refresh.sh
#   Renovate   a `postUpgradeTasks` command on every kube-prometheus-stack branch
#              (.github/renovate-global.json), so a chart bump is BORN with the list re-rendered and
#              CI is green at birth unless the new chart adds an alert NAME — then the lint names
#              it and the `deps-review` worker-adapts leg classifies it (#2225/#2245 were the two
#              hand runs this replaces).
# The Renovate container is the SLIM image (containerbase + jq + a runtime `install-tool`; no yq,
# no python, no devbox), so this script is deliberately yq-free: helm renders per template into a
# directory (`--output-dir`), the alert names are grepped from the upstream rule files, and the
# `defaultRules` fingerprint is a hash over that values subtree as TEXT (comments and blank lines
# stripped) — prometheus-rules-lint.sh computes the SAME fingerprint (its twin, named there), so a
# change to this recipe changes both in the same commit. Tools: bash, helm 4.x (`install-tool helm`
# in the Renovate container, devbox here), coreutils, grep, sed, awk.
set -euo pipefail
cd "$(dirname "$0")/.."
app=argocd/platform/kube-prometheus-stack.yaml
values=argocd/platform/values/kube-prometheus-stack.yaml
out=argocd/platform/values/kube-prometheus-stack-upstream-alerts.txt
# The chart source block of the Application: `- repoURL:` … `chart: kube-prometheus-stack` …
# `targetRevision:` (one chart source per Application by design; the pin-only lane keys on the same
# `targetRevision:` line). The repoURL is the one that precedes the chart line.
repo=$(awk '/^[[:space:]]*-?[[:space:]]*repoURL:/{r=$NF} /^[[:space:]]*chart:[[:space:]]*kube-prometheus-stack[[:space:]]*$/{print r; exit}' "$app")
ver=$(awk '/^[[:space:]]*chart:[[:space:]]*kube-prometheus-stack[[:space:]]*$/{f=1} f&&/^[[:space:]]*targetRevision:/{gsub(/"/,"",$2); print $2; exit}' "$app")
[ -n "$ver" ] && [ -n "$repo" ] || { echo "upstream-alerts-refresh: no pinned chart version/repo in $app" >&2; exit 2; }
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
helm pull kube-prometheus-stack --repo "$repo" --version "$ver" --untar --untardir "$tmp" >/dev/null
# One file per rendered template (templates that render nothing are not written); our own rule
# groups (`additionalPrometheusRulesMap`) all render through templates/prometheus/additionalPrometheusRules.yaml
# and are excluded by that path — every other rendered file (the chart's rules-1.14/*, any subchart
# rules) is upstream.
helm template kps "$tmp/kube-prometheus-stack" -f "$values" --namespace monitoring --output-dir "$tmp/out" >/dev/null
names=$(find "$tmp/out" -name '*.yaml' ! -name 'additionalPrometheusRules.yaml' -print0 \
  | xargs -0 grep -hE '^[[:space:]]*- alert:[[:space:]]' \
  | sed -E 's/^[[:space:]]*- alert:[[:space:]]*"?([^"[:space:]]+)"?.*/\1/' | LC_ALL=C sort -u)
[ -n "$names" ] || { echo "upstream-alerts-refresh: rendered zero upstream alerts — refusing to write an empty list" >&2; exit 2; }
# the defaultRules fingerprint — TWIN of the one in scripts/prometheus-rules-lint.sh (keep identical)
dr_hash=$(awk '/^defaultRules:/{f=1; print; next} f&&/^[^[:space:]#]/{exit} f' "$values" | grep -vE '^[[:space:]]*(#|$)' | sha256sum | cut -c1-12)
{
  echo "# chart: kube-prometheus-stack $ver — every alert the PINNED chart renders with our values (the values file's own rule groups excluded)."
  echo "# Generated by scripts/upstream-alerts-refresh.sh; do not hand-edit. Each name needs one entry in kube-prometheus-stack-triage.yaml."
  echo "# defaultRules: $dr_hash"
  printf '%s\n' "$names"
} > "$out"
echo "upstream-alerts-refresh: $(printf '%s\n' "$names" | wc -l) alert(s) for chart $ver → $out"
